app/__init__.py
from flask import Flask
from flask_cors import CORS
from flask_session import Session

from .site.routes import site

app = Flask(__name__)
CORS(app)

Session(app)

app.register_blueprint(site)

if __name__ == '__main__':
    app.run(debug=True)

app/site/routes.py
from flask import Blueprint, render_template, redirect
# import sys
# import os


# sys.path.append("/app")


from ..state_dict_folder.state_dict import full_state_dictionary, sorted_pop, sorted_land_area
from ..state_dict_folder.gov_dict import gov_dictionary
from ..state_dict_folder.ebird_dict import bird_dict

site = Blueprint('site',__name__, template_folder='site_pages')

@site.route('/')
@site.route('/home')
def home():
    return render_template('index.html', full_state_dictionary = full_state_dictionary)


@site.route('/birds')
def birds():
    return render_template('birds.html', full_state_dictionary=full_state_dictionary)

@site.route('/state/<state_code>')
def state(state_code):
    state_data = full_state_dictionary.get(state_code)
    gov_data = gov_dictionary.get(state_code)
    bird_data = bird_dict.get(state_code)
    if state_data:
        return render_template('state.html', 
                               full_state_dictionary=full_state_dictionary, 
                               gov_data=gov_data, state_data=state_data, 
                               sorted_pop=sorted_pop, 
                               sorted_land_area=sorted_land_area,
                               bird_data=bird_data)
    else:
        # TODO build out 404 functionality
        return render_template('404.html')
            

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{url_for('static', filename='dist/css/output.css')}}">
<link rel="stylesheet" href="../static/dist/css/style.css">


<title>State Stats</title>
<script async
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB022q1pB4wYXEJ6fOE3GQFRT-RwcicOFU&callback=initMap&libraries=maps,marker&v=beta">
</script>



</head>
<body class="bg-light-gold">
    <nav class="w-full bg-dark-blue h-1/3 py-4">
        <div class="container">
            <a href="{{ url_for('site.home') }}"><p class="light-gold">Home</p></a>
        </div>
    </nav>

    {% block content %}
<!-- TODO: figure out nav bar -->

{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/gpt.html
{% extends 'base.html' %}

{% block content %}
<style>
#main-area {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;}

img {
    display: block;
}

    .image-container {
    position: relative;
    display: inline-block;
}




</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const map = document.getElementById('map');
    const areas = map.querySelectorAll('area');
    
    areas.forEach(area => {
        area.addEventListener('mouseover', function() {
            const hoverColor = this.dataset.hovercolor || 'lightcoral';
            this.style.backgroundColor = hoverColor;
        });
        
        area.addEventListener('mouseout', function() {
            this.style.backgroundColor = 'transparent';
        });
    });
});


</script>


<div id="main-area" class="image-container"> 
  <img src="../static/img/blank_map.png" alt="Image with Clickable Areas" usemap="#map">
    
    <map name="map" id="map">
        <area shape="rect" coords="10,10,50,50" data-hovercolor="lightcoral">
        <!-- Add more areas with different shapes and coordinates -->
    </map>
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block content %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const searchInput = document.getElementById('searchInput');
        const resultsContainer = document.getElementById('results');
        const stateFlowers = {{ full_state_dictionary }}
        console.log('this is the state flower', stateFlowers)

        function updateResults(searchTerm) {
            resultsContainer.innerHTML = ''; // Clear previous results
    
            stateFlowers.forEach(pair => {
                if (pair.flower.includes(searchTerm.toLowerCase())) {
                    const listItem = document.createElement('li');
                    listItem.textContent = `${pair.state}: ${pair.flower}`;
                    resultsContainer.appendChild(listItem);
                }
            });
        }
    
        searchInput.addEventListener('input', function() {
            const searchTerm = this.value.trim();
            updateResults(searchTerm);
        });
    });
    
</script>

    <h1>Search for State Flowers  <input type="text" id="searchInput" placeholder="Search for a flower..."></h1>
   
    <ul id="results">
        {% for k,v in full_state_dictionary.items() %}
        <li id="flowers">{{ v['name'] }}: {{ v['flower'] }}</li>
        {% endfor %}
    </ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{{url_for('static', filename='dist/css/output.css')}}">
<link rel="stylesheet" href="../static/dist/css/style.css">


<title>State Stats</title>
<script async
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB022q1pB4wYXEJ6fOE3GQFRT-RwcicOFU&callback=initMap&libraries=maps,marker&v=beta">
</script>



</head>
<body>
{% block content %}

{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %} 

{% block content %}

<script type="text/javascript"
src="{{ url_for('static', filename='scripts.js') }}"></script>

<!-- starting main div wrapper -->
<div class="container w-11/12 mt-7">

<!-- state list and map area -->
    <div class="flex flex-row container">
        <div class="w-3/12 bg-gray-100 pl-4 py-2 h-96 overflow-scroll">
            <ul>
                {% for k,v in full_state_dictionary.items() %}
                <li id="{{ v['name'] }}" onclick="">
                    {{ v['name'] }}
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="w-9/12">
            <script>
                function initMap() {
            
                  const advancedMarkers = document.querySelectorAll("#marker-click-event-example gmp-advanced-marker");
                  for (const advancedMarker of advancedMarkers) {
                    customElements.whenDefined(advancedMarker.localName).then(async () => {
                      advancedMarker.addEventListener('gmp-click', async () => {
                        const {InfoWindow} = await google.maps.importLibrary("maps");
                        const infoWindow = new InfoWindow({
                          content: advancedMarker.title
                        });
                        infoWindow.open({
                          anchor: advancedMarker
                        });
                      });
                    });
                  }
                }

            </script>
            <script>
                function myFunction() {
                    document.getElementById("test-area").style.backgroundColor = "red";
                }
            </script>

            <gmp-map id="marker-click-event-example" center="40.808075,-96.699654" zoom="4" map-id="DEMO_MAP_ID">
                {% for k,v in full_state_dictionary.items() %}
                    <gmp-advanced-marker position="{{ v['lat'] }},{{ v['lon'] }}" title="{{v['capital']}}, {{ v['name'] }}"></gmp-advanced-marker>
                {% endfor %}
            </gmp-map>
        </div>
    </div>

</div>

<div class=" container w-11/12 mt-5">
    <div class="container flex flex-row">

        <!-- start land area scroll -->
        <div class="w-12/12 mx-2">
            <div class="border-b-2 mb-1">
                <p class="text-lg font-sans text-center">
                    State Stats
                </p>
            </div>
            <!-- TODO: troubleshoot search bar -->
            <!-- <input type="text" class="border rounded border-gray-400 mb-2" id="state_search" onkeyup="stateSearch()" placeholder="Search for a state"> -->
            
            <div class="h-96 overflow-scroll">
                <table id="state-area" class="table-style table-sort">
                    <tr class="">
                        <th class="table-header" onclick="">State Name</th>
                        <th class="">Land Area</th>
                        <th class="">Population</th>
                        <th class="">Governor</th>
                        <th class="">State Flower</th>
                        <th class="">State Bird</th>
                    </tr>

                    {% for k,v in full_state_dictionary.items() %}
                    <tr>
                        <td class="state-name">{{ v['name'] }}</td>
                        <td>{{ v['land_area'] }}</td>
                        <td>
                            <p>{{ v['population'] }}</p>
                        </td>
                        <td>
                            <p>{{ v['governor'] }}</p>
                        </td>
                        <td>
                            <p>{{ v['flower'] }}</p>
                        </td>
                        <td>
                            <p>{{ v['bird'] }}</p>
                        </td>
                    </tr>
                    {% endfor %}
                </table>     
            </div>
        </div>
        <!-- end land area scroll -->

</div>
<!-- ending main div wrapper -->
{% endblock %}